### ISSUE TITLE
Default value has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.onkyo#101]
onkyo 2.1.1
js-controller 4.0.5
nodejs 14.19.0

> 2022-02-09 11:16:20.807 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaTimeCurrent is invalid: Default value has to be type "number" but received type "string"
> 2022-02-09 11:16:20.808 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.813 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaTime is invalid: Default value has to be type "number" but received type "string"
> 2022-02-09 11:16:20.813 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.830 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaStop is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.831 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.836 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaPlay is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.837 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.842 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaPause is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.842 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.846 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaForward is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.847 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.851 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaFastForward is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.851 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.855 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaReverse is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.856 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.859 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaFastReverse is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.860 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.863 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaRepeat is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.864 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.879 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaTrackUp is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.879 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.884 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaTrackDown is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.884 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.889 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaRight is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.889 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.894 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaLeft is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.895 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.900 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaUp is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.900 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.905 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaDown is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.905 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.910 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaSelect is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.910 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.915 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaDelete is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.915 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.920 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaReturn is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.920 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.925 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaMenu is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.926 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.
> 2022-02-09 11:16:20.930 - warn: onkyo.0 (1517) Object onkyo.0.Device.MediaTop is invalid: Default value has to be type "boolean" but received type "string"
> 2022-02-09 11:16:20.930 - warn: onkyo.0 (1517) This object will not be created in future versions. Please report this to the developer.

**Comment by Apollon77** [comment]
fixed in next release
