### ISSUE TITLE
command seems not to work

### ISSUE THREAD

**Issue by DeadBoolean** [ioBroker/ioBroker.onkyo#31]
Hello,

fist i like to say good work at all.

But in my case the "command" funktion seems not to work. 

If i write i.E. "PWR00" or "system-power=off" it changed to 0 and noting happens.
It works, if i am using the system-power node directy.

in the log, this error ist listed:

onkyo.0 | 2018-08-03 17:59:20.690 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
onkyo.0 | 2018-08-03 17:59:20.690 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
onkyo.0 | 2018-08-03 17:59:20.690 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)

Hope you can help.

**Comment by Eisbaeeer** [comment]
Hi DeadBoolean
We are working on the Onkyo adapter. You can try this develop version instead, until the new version will be published. But have in mind, that this is a develop version. Some things will be changed.
https://gitbhub.com/Eisbaeeer/ioBroker.onkyo-vis

**Comment by DeadBoolean** [comment]
Hallo,

danke für Deine Mühe.
Leider geht es damit auch nicht. 

Gruß Sascha

**Comment by Eisbaeeer** [comment]
Doch geht. Schreib den Wert in das Objekt RAW.

**Comment by Eisbaeeer** [comment]
Sollte im Objekt RAW funktionieren. Bitte kurzes feedback.
