### ISSUE TITLE
Add support for Pioneer devices, that base on Onkyo hardware

### ISSUE THREAD

**Issue by ooooli** [ioBroker/ioBroker.onkyo#32]
Using a Pioneer VSX-1131, I did not have a chance to use ioBroker. The Pioneer adapter doesn't support the Onkyo protocol. The Onkyo Adapter misses the Pioneer packets. 
I added the packet manually, but would prefer to have it implemented in the adapter (also for other users).

Changes to be implemented:
https://github.com/miracle2k/onkyo-eiscp/pull/67/files

Thread in forum:
https://forum.iobroker.net/viewtopic.php?f=20&t=9194#p139212

**Comment by Apollon77** [comment]
Cool, simply create a Pull-Request?!

**Comment by Eisbaeeer** [comment]
Pioneer support added
