### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.onkyo#33]
host.SERVER | 2018-11-24 14:02:34.538 | error | instance system.adapter.onkyo.0 terminated with code 1 ()
-- | -- | -- | --
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at bootstrap_node.js:496:3
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at startup (bootstrap_node.js:149:9)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at run (bootstrap_node.js:383:7)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at Module.runMain (module.js:604:10)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at Function.Module._load (module.js:438:3)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at tryModuleLoad (module.js:446:12)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at Module.load (module.js:487:32)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:579:10)
host.SERVER | 2018-11-24 14:02:34.538 | error | Caught by controller[0]: at Module._compile (module.js:570:32)
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]: at Object.<anonymous> (C:\ioBroker\node_modules\iobroker.onkyo\onkyo.js:14:17)
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]: TypeError: utils.Adapter is not a constructor
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]:
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]: ^
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]: const adapter = new utils.Adapter('onkyo'); // name has to be set and has to be equal to adapters folder name and main file name excluding extension
host.SERVER | 2018-11-24 14:02:34.523 | error | Caught by controller[0]: C:\ioBroker\node_modules\iobroker.onkyo\onkyo.js:14

**Comment by Apollon77** [comment]
try 2.0.1 on github please

**Comment by Apollon77** [comment]
please try 2.0.1 >14:45 :-)
