### ISSUE TITLE
TunerPresets DAB issue

### ISSUE THREAD

**Issue by Strobelix80** [ioBroker/ioBroker.onkyo#35]
While using DAB Radio (In33) it isn‘t possible changing Tuner Presets. Changing Presets sets Input automatically to FM (In24)

**Comment by Eisbaeeer** [comment]
Wich model do you using? Is there an extra command for DAB preset?
The adapter supports actually two modes of presets. FM and streaming.
Greets Eisbaeeer

**Comment by Strobelix80** [comment]
I got a bit time now to check something.
I use a Pioneer VXS-S520D

With the old onky-vis-dev Adapter it was possible to set the Input to 33 (DAB) and then change the DAB Tuner Presets with the Zone1 command „TunerPreset“ (so this command works for FM and DAB)

With the new Adapter the receiver always changes the Input to 24 (FM) when changing the „TunerPreset“. It seems to me, that changing the Tunerpreset also triggers a Input change to 24?!

With a RAW command like „PRS02“ the receiver stays on input 33 and only changes to DAB Preset 2. So in my opinion there is a input-change-bug in the TunerPreset command?

**Comment by Eisbaeeer** [comment]
You are right. There was a small change. It´s by design. If you call a preset, the corrosponding input will be selected, too. Now it seems, that the pioneer input differs from the onkyo input value.
I will revert this feature to get compatible with pioneer. So no input will be selected if a tuner preset is called in the next version.

**Comment by Strobelix80** [comment]
Thanks! I use this workaround by changing SLI24 to SLI33 because i only use DAB Presets.
Works great!

**Comment by kr0815** [comment]
after 5 years, i came acros the same problem - seems it never was fixed

If you prefer DAB over FM, change SLI24 to SLI33

Maybe it helps someone
