### ISSUE TITLE
Changing the Input on a Pioneer AVR

### ISSUE THREAD

**Issue by B0bb3rl3** [ioBroker/ioBroker.onkyo#39]
Is there a possibility to change the Input of an Pioneer AVR?
Like to change it from AUX to BT or others?

**Comment by B0bb3rl3** [comment]
Is there still no possibility even with the command ?

**Comment by Eisbaeeer** [comment]
It depends on your model of AV Receiver. Does it support the EISCP protocol?
Do you get any objects from your receiver?
greetings Eisbaeeer
