### ISSUE TITLE
Add Support for ListenModeStereo

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.onkyo#42]
There is actually no object to switch ListenMode to Stereo

**Comment by Apollon77** [comment]
I updted the supported commands ... maybe this helps? Try GitHub version please (manual restart after update)

**Comment by darkiop** [comment]
my onkyo is unfortunately no longer in use. had problems with the one power amp and it was replaced by a big yamaha :)

**Comment by ice987987** [comment]
tested with Onkyo TX-NR656:
`onkyo.0.Device.RAW`: `LMD00` sets STEREO
`onkyo.0.Device.RAW`: `LMD01` sets DIRECT 
`onkyo.0.Device.RAW`: `LMD02` sets SURROUND
`onkyo.0.Device.RAW`: `LMD03` sets FILM Game-RPG
`onkyo.0.Device.RAW`: `LMD05` sets ACTION Game-Action
`onkyo.0.Device.RAW`: `LMD06` sets MUSICAL Game-Rock
`onkyo.0.Device.RAW`: `LMD08` sets ORCHESTRA
`onkyo.0.Device.RAW`: `LMD09` sets UNPLUGGED
`onkyo.0.Device.RAW`: `LMD0A` sets STUDIO-MIX
`onkyo.0.Device.RAW`: `LMD0B` sets TV LOGIC
`onkyo.0.Device.RAW`: `LMD0C` sets ALL CH STEREO
`onkyo.0.Device.RAW`: `LMD0D` sets THEATER-DIMENSIONAL 
`onkyo.0.Device.RAW`: `LMD0E` sets ENHANCED 7/ENHANCE Game-Sports
`onkyo.0.Device.RAW`: `LMD11` sets PURE AUDIO 
`onkyo.0.Device.RAW`: `LMD13` sets FULL MONO
`onkyo.0.Device.RAW`: `LMD40` sets DolbyDigital
`onkyo.0.Device.RAW`: `LMD80` sets PLII/PLIIx Movie Dolby Atmos/Dolby Surround
`onkyo.0.Device.RAW`: `LMDUP` sets Listening Mode Wrap-Around Up
`onkyo.0.Device.RAW`: `LMDDOWN` sets Listening Mode Wrap-Around Down
`onkyo.0.Device.RAW`: `LMDMOVIE` sets Listening Mode Wrap-Around Up
`onkyo.0.Device.RAW`: `LMDMUSIC` sets Listening Mode Wrap-Around Up
`onkyo.0.Device.RAW`: `LMDGAME` sets Listening Mode Wrap-Around Up

**Comment by Apollon77** [comment]
so works?

**Comment by ice987987** [comment]
In my point of view: issue solved.
