### ISSUE TITLE
Onkyo TX-NR535

### ISSUE THREAD

**Issue by Carsten0809** [ioBroker/ioBroker.onkyo#50]
Seit ein paar Tagen taucht permanent folgende Fehlermeldung im log auf:

```
onkyo.0 | 2021-01-31 15:56:03.247 | info | (14057) Successfully connected to AVR
-- | -- | -- | --
onkyo.0 | 2021-01-31 15:55:58.218 | info | (14057) AVR disconnected
onkyo.0 | 2021-01-31 15:55:58.217 | error | }
onkyo.0 | 2021-01-31 15:55:58.217 | error | syscall: 'read'
onkyo.0 | 2021-01-31 15:55:58.217 | error | code: 'ECONNRESET',
onkyo.0 | 2021-01-31 15:55:58.217 | error | errno: 'ECONNRESET',
onkyo.0 | 2021-01-31 15:55:58.217 | error | at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
onkyo.0 | 2021-01-31 15:55:58.217 | error | (14057) Error: ERROR (server_error) Server error on 192.168.0.27:60128 - Error: read ECONNRESET
```

Am System habe ich nichts geändert, der AV-Receiver reagiert auch noch auf Befehle aus iobroker - nur das zumüllen des Logs nervt. Wurde etwas geändert?

**Comment by Apollon77** [comment]
> Wurde etwas geändert?

Hast Du ein update inszalliert? ECONNRESET heisst das dein AVR die Verbindung killt. Vllt mal stromlos machen und neu starten? AM Ende keine AHnugn was ich jetzt hier sagen soll :-)
