### ISSUE TITLE
Missing CoverImage.bmp is resetting the instance

### ISSUE THREAD

**Issue by DominikReber** [ioBroker/ioBroker.onkyo#51]
Hi

Works really good except for this error which is restarting the adapter:

`

onkyo.0 | 2021-04-07 09:15:32.822 | info | (13356) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
onkyo.0 | 2021-04-07 09:15:32.821 | info | (13356) terminating
onkyo.0 | 2021-04-07 09:15:32.811 | info | (13356) AVR disconnected
onkyo.0 | 2021-04-07 09:15:32.808 | error | at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at Socket.Readable.push (_stream_readable.js:213:10)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at readableAddChunk (_stream_readable.js:272:9)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at addChunk (_stream_readable.js:297:12)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at Socket.emit (events.js:314:20)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/eiscp/eiscp.js:384:8)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at EventEmitter.emit (events.js:314:20)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at EventEmitter.<anonymous> (/opt/iobroker/node_modules/iobroker.onkyo/main.js:999:7)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at Object.writeFileSync (fs.js:1384:35)
onkyo.0 | 2021-04-07 09:15:32.808 | error | at Object.openSync (fs.js:462:3)
onkyo.0 | 2021-04-07 09:15:32.808 | error | (13356) Error: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/vis/CoverImage.bmp'

`

Somehow he cannot open the CoverImage.bmp. Could you please try/catch this error? I dont need the image anyways but it keeps my adapter/instance resetting. 

Thanks

Dominik

**Comment by Videonisse** [comment]
You can get rid of the error if you install an Instance of the Adapter VIS (Visualisation). You can then keep it deactivated if you don't need it. https://github.com/iobroker/iobroker.vis/blob/master/README.md

**Comment by DominikReber** [comment]
Thanks

**Comment by Apollon77** [comment]
Plesse try GitHub version
