### ISSUE TITLE
"This object will not be created in future versions. Please report this to the developer."

### ISSUE THREAD

**Issue by DominikReber** [ioBroker/ioBroker.onkyo#52]
TX-NR636 I get this note/warning at startup:

`

onkyo.0 | 2021-04-07 09:18:01.709 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
onkyo.0 | 2021-04-07 09:18:01.709 | warn | (13742) Object onkyo.0.Device.CoverURL is invalid: obj.common.type has an invalid value (media.cover) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-04-07 09:18:01.705 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-04-07 09:18:01.705 | warn | (13742) Object onkyo.0.Device.CoverBase64 is invalid: obj.common.type has an invalid value (media.cover) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-04-07 09:18:01.215 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-04-07 09:18:01.215 | warn | (13742) Object onkyo.0.Device.MediaState is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-04-07 09:18:00.530 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-04-07 09:18:00.530 | warn | (13742) Object onkyo.0.Zone3 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f
onkyo.0 | 2021-04-07 09:18:00.525 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-04-07 09:18:00.524 | warn | (13742) Object onkyo.0.Zone2 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f
onkyo.0 | 2021-04-07 09:18:00.519 | warn | (13742) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-04-07 09:18:00.516 | warn | (13742) Object onkyo.0.Zone1 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f

`

**Comment by Videonisse** [comment]
This has already been reported in Issue #48 in April 2020: https://github.com/ioBroker/ioBroker.onkyo/issues/48

Unfortunately still open.

**Comment by Apollon77** [comment]
should be fixed since 27.4.
