### ISSUE TITLE
Question: In ioBroker I see the instanz and object of Onkyo, but where would I see the PNGs in iobroker or how to implement these?

### ISSUE THREAD

**Issue by AIXruth** [ioBroker/ioBroker.onkyo#91]
Question: In ioBroker I see the instanz and object of Onkyo, but where would I see the PNGs in iobroker or how to implement these?

Any hint, clue or further references/documentation would be great!

**Comment by ice987987** [comment]
What do you exactly mean with "PNGs"? Do you mean the Cover-Picture?
f.ex.:
`onkyo.0.Device.CoverBase64`
`onkyo.0.Device.CoverURL`

**Comment by AIXruth** [comment]
I wonder, if there is already a prepared Vis (GUI) which could be used, like a remote controller and yes, like the cover pictures.

**Comment by ice987987** [comment]
The cover picture can f.ex. displayed with the following widget from [ioBroker.vis](https://github.com/ioBroker/ioBroker.vis):

`[{"tpl":"tplValueStringRaw","data":{"oid":"onkyo.0.Device.CoverBase64","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide"},"style":{"left":"100px","top":"100px","width":"200px","height":"200px","z-index":"1"},"widgetSet":"basic"}]`

For the GUI, can probably find something in https://forum.iobroker.net.
